using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Loom.Generators
{
    [Generator(LanguageNames.CSharp)]
    public sealed class ComponentAccessorGenerator : IIncrementalGenerator
    {
        private const string AttributeMetadataName = "Loom.Components.EcsComponentAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<ComponentModel?> components = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AttributeMetadataName,
                    predicate: static (node, _) => node is StructDeclarationSyntax,
                    transform: static (ctx, _) =>
                    {
                        if (ctx.TargetSymbol is not INamedTypeSymbol symbol || !symbol.IsValueType)
                            return null;

                        string fullyQualified = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        string propertyName = symbol.Name;
                        return new ComponentModel(fullyQualified, propertyName);
                    });

            IncrementalValueProvider<ImmutableArray<ComponentModel?>> collected = components.Collect();

            context.RegisterSourceOutput(collected, static (spc, items) =>
            {
                var list = new List<ComponentModel>();
                var seenNames = new HashSet<string>(StringComparer.Ordinal);
                foreach (ComponentModel? item in items)
                {
                    if (item == null)
                        continue;
                    if (!seenNames.Add(item.PropertyName))
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(
                            new DiagnosticDescriptor(
                                "LOOM001",
                                "Duplicate EcsComponent short name",
                                "Multiple [EcsComponent] structs named '{0}' in this compilation; rename one type or nest it so property names stay unique.",
                                "Loom",
                                DiagnosticSeverity.Error,
                                isEnabledByDefault: true),
                            Location.None,
                            item.PropertyName));
                        return;
                    }

                    list.Add(item);
                }

                if (list.Count == 0)
                    return;

                list.Sort((a, b) => string.CompareOrdinal(a.PropertyName, b.PropertyName));
                spc.AddSource("Loom.ComponentAccess.g.cs", SourceText.From(Generate(list), Encoding.UTF8));
            });
        }

        private static string Generate(List<ComponentModel> components)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Loom.Entities;");
            sb.AppendLine("namespace Loom.Components");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Typed component accessors generated from <see cref=\"EcsComponentAttribute\"/>.</summary>");
            sb.AppendLine("    public readonly ref struct ComponentAccess");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly World _world;");
            sb.AppendLine("        private readonly Entity _entity;");
            sb.AppendLine();
            sb.AppendLine("        public ComponentAccess(World world, Entity entity)");
            sb.AppendLine("        {");
            sb.AppendLine("            _world = world;");
            sb.AppendLine("            _entity = entity;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public Entity Entity => _entity;");
            sb.AppendLine();

            foreach (ComponentModel c in components)
            {
                sb.AppendLine($"        public ref {c.FullyQualified} {c.PropertyName} => ref _world.Get<{c.FullyQualified}>(_entity);");
                sb.AppendLine($"        public bool Has{c.PropertyName} => _world.Has<{c.FullyQualified}>(_entity);");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static class ComponentAccessExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>Non-generic entry point: <c>world.Get(entity).Position</c> for");
            sb.AppendLine("        /// types marked <see cref=\"EcsComponentAttribute\"/>. Distinct from");
            sb.AppendLine("        /// <see cref=\"World.Get{T}(Entity)\"/> which still needs a type argument.</summary>");
            sb.AppendLine("        public static ComponentAccess Get(this World world, Entity entity) => new ComponentAccess(world, entity);");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private sealed class ComponentModel
        {
            public readonly string FullyQualified;
            public readonly string PropertyName;

            public ComponentModel(string fullyQualified, string propertyName)
            {
                FullyQualified = fullyQualified;
                PropertyName = propertyName;
            }
        }
    }
}
